apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      imagePullSecrets:
        - name: ecr-secret  # 👈 Add this line
      containers:
        - name: spring-boot-app
          image: 515966517171.dkr.ecr.us-east-1.amazonaws.com/voting:78
          ports:
            - containerPort: 8080
